version: '3.9'
services:
  mysql:
    container_name: todo-app-mysql
    image: mysql:5.7.42
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - todo-app-volume:/var/lib/mysql
    networks:
      - todo-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "todo-app-mysql"]
      timeout: 5s
      retries: 5
  server:
    container_name: todo-app-apache
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

networks:
  todo-app-network:
    driver: bridge
    name: todo-app-network

volumes:
  todo-app-volume:
    driver: local
    name: todo-app-volume
